const roomQualityArray = [
    //{trait: "High Friction", weight: 2},  
    {trait: "Low Friction", weight: 2},
    {trait: "Subjective Gravity", weight: 5},
    {trait: "Variable Gravity", weight: 5},
    {trait: "Enhanced Gravity", weight: 1},
    {trait: "Reduced Gravity", weight: 5},
    {trait: "Zero Gravity", weight: 5},
    {trait: "Inverted Gravity", weight: 2},
    {trait: "Magic Enhancing", weight: 2},
    {trait: "Magic Dampening", weight: 1},
    {trait: "Magic Nullifying", weight: 1},
    {trait: "Wild Magic", weight: 2},
    {trait: "Energetic Magic", weight: 2},
    {trait: "Psi Enhancing", weight: 2},
    {trait: "Psi Dampening", weight: 1},
    {trait: "Psi Nullifying", weight: 1},
    {trait: "Empathic Links", weight: 2},
    {trait: "Qi Enhancing", weight: 1}, // 40
    {trait: "Qi Dampening", weight: 1},
    {trait: "Qi Nullifying", weight: 1},
    {trait: "Tech Jamming", weight: 1},
    {trait: "Pheromones", weight: 5},
    {trait: "Calming", weight: 5},
    {trait: "Dizzying", weight: 5},
    {trait: "Arousing", weight: 5},
    {trait: "Giddiness", weight: 5},
    {trait: "Illusory Clones", weight: 1},
    {trait: "Sub/Dom Flip", weight: 1}, // 70
    {trait: "Submissiveness Boosting", weight: 1},
    {trait: "Dominance Boosting", weight: 1},
    {trait: "Temporary Sex Change", weight: 5},
    {trait: "Afterimages", weight: 1},
    {trait: "Lust-Triggering Decor/Architecture", weight: 5},
    {trait: "Overtly Hypnotic Decor/Architecture", weight: 5},
    {trait: "Hypnotic Traps", weight: 5},
    {trait: "Soft Music", weight: 4},
    {trait: "Soft Hypnotic Music", weight: 5},
    {trait: "Inverted Controls", weight: 1},
    {trait: "Furniture on Walls", weight: 1},
    {trait: "Deceptive Distances", weight: 5},
    {trait: "Localized Portals", weight: 5},
    {trait: "Walls/Floor/Furniture Contains Mimic", weight: 2},
    {trait: "Mindless Clone", weight: 5},
    {trait: "Hypnotic/Arousing Body Parts", weight: 5},
    {trait: "Hypnotic Feedback", weight: 5},
    {trait: "IQ Lowering", weight: 5},
    {trait: "Soporific", weight: 5},
    {trait: "Energy Draining", weight: 5},
    {trait: "Clothes-Transforming", weight: 5},
    {trait: "Clothes-Destroying", weight: 5},
    {trait: "Increased Sensitivity", weight: 5},
    {trait: "Vertigo", weight: 5},
    {trait: "Numbing", weight: 5},
    {trait: "Animal Ears", weight: 5},
    {trait: "Abilities Gain \"Hypnotic\" Modifier", weight: 5},
    {trait: "Persistent Sourceless Sound", weight: 10},
    {trait: "Suggestibility Aura", weight: 10},
    {trait: "Haunted", weight: 20},
    {trait: "Room-Restricted Hypno-Accessories", weight: 20},
    {trait: "Colossal Sized Room/Furniture", weight: 50},
    {trait: "Tiny Room/Furniture", weight: 50}
];

const roomQualityCount = 341;

exports.roomQualityArray = roomQualityArray;
exports.roomQualityCount = roomQualityCount;